### PR TITLE
Feat/add servicos

### PR DESCRIPTION
**Pull request by osmaclean**
Key property added to map method in "Session Services" component. Added "alt" and "aria-label" properties for user accessibility. Fixed some Tailwind properties.

### CODE REVIEW

**Comment by cleidson-os** [comment]
### Improvement points:

- Create static types for ServiceCard and SessionService components props

- Rather then to use , use <Image /> Next component. It's optimized to work in NextJs.
[NextJs docs - Image component](https://nextjs.org/docs/pages/api-reference/components/image)

- Insted of criating css files to add new css rules, when using Tailwind it's a best pratice to use @layer directive.
[Tailwind docs - @layer directive](https://tailwindcss.com/docs/adding-custom-styles#using-css-and-layer)

**Review by lubias — APPROVED** [review]
Ok

**Comment by RaphaelMarquesMartorella** [comment]
Ok

**Comment by cleidson-os** [comment]
ok

**Pull request merged**
